name: Restrict PRs to Main
on:
  pull_request:
    branches:
      - main
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Pull requests to 'main' must come from 'develop' branch only."
            exit 1
          fi