name: Restringir PRs para Main
on:
  pull_request:
    branches:
      - main
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        run: |
          exit 1