name: Restringir PRs para Main
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" && ${{ github.event.pull_request.base.ref }} == "main"]]; then
            echo "Solicitações de pull request para a branch 'main' devem vir somente da branch 'develop'."
            exit 1
          fi